name: Automatic Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if required for tooling)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Bump version and create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          current_version=$(git tag --list | sort -V | tail -n 1)
          next_version=$(echo $current_version | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo "Current version: $current_version, Next version: $next_version"
          git tag $next_version
          git push origin $next_version
